config/routes.rb
Rails.application.routes.draw do
  root to: "usuarios#index"

  # RedefinirSenha controller
  get 'redefinir_senha/busca', to: "redefinir_senha#busca", as: :redefinir_senha
  post 'redefinir_senha/busca', to: "redefinir_senha#recuperar"

  # Comentarios controller
  resources :comentarios

  # Posts controller
  patch 'curtir/:post_id', to: "posts#curtir", as: :curtir
  patch 'descurtir/:post_id', to: "posts#descurtir", as: :descurtir
  get 'feed', to: "posts#feed", as: :feed
  resources :posts

  # Sessoes controller
  get 'login', to: "sessoes#new", as: :login
  post 'login', to: "sessoes#create"
  delete 'logout', to: "sessoes#destroy", as: :logout

  # Usuarios controller
  patch 'buscacidades', to: "usuarios#buscacidades", as: :buscacidades
  get 'usuarios/novo', to: "usuarios#new", as: :new_usuario
  post 'usuarios/novo', to: "usuarios#create"
  get 'usuarios/editar/:id', to: "usuarios#edit", as: :edit_usuario
  patch 'usuarios/editar/:id', to: "usuarios#update"
  # ao se utilizar rotas que possuem parametros, coloca-las por ultimo
  # se não o Rails vai confundir o nome da rota com um parametro
  get 'usuarios/:id', to: "usuarios#show", as: :show_usuario
  delete 'usuarios/:id', to: "usuarios#destroy", as: :destroy_usuario
  get 'usuarios', to: "usuarios#index", as: :index_usuarios

end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :usuario
  belongs_to :post
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to post_path(id: @comentario.post.id),
          notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        @post = @comentario.post
        format.html { render "posts/show" }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:usuario_id, :post_id, :conteudo)
    end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_form.html.erb
<%= form_with(model: comentario, local: true) do |form| %>

  <%= hidden_field_tag "comentario[usuario_id]", current_user.id %>

  <%= hidden_field_tag "comentario[post_id]", params[:id] %>

  <div class="field">
    <%= form.label :conteudo %>
    <%= form.text_field :conteudo, id: :comentario_conteudo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Post</th>
      <th>Conteudo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.usuario %></td>
        <td><%= comentario.post %></td>
        <td><%= comentario.conteudo %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @comentario.usuario %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comentario.post %>
</p>

<p>
  <strong>Conteudo:</strong>
  <%= @comentario.conteudo %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>