config/routes.rb
Rails.application.routes.draw do
  root to: "usuarios#index"

  # RedefinirSenha controller
  get 'redefinir_senha/busca', to: "redefinir_senha#busca", as: :redefinir_senha
  post 'redefinir_senha/busca', to: "redefinir_senha#recuperar"

  # Comentarios controller
  resources :comentarios

  # Posts controller
  patch 'curtir/:post_id', to: "posts#curtir", as: :curtir
  patch 'descurtir/:post_id', to: "posts#descurtir", as: :descurtir
  get 'feed', to: "posts#feed", as: :feed
  resources :posts

  # Sessoes controller
  get 'login', to: "sessoes#new", as: :login
  post 'login', to: "sessoes#create"
  delete 'logout', to: "sessoes#destroy", as: :logout

  # Usuarios controller
  patch 'buscacidades', to: "usuarios#buscacidades", as: :buscacidades
  get 'usuarios/novo', to: "usuarios#new", as: :new_usuario
  post 'usuarios/novo', to: "usuarios#create"
  get 'usuarios/editar/:id', to: "usuarios#edit", as: :edit_usuario
  patch 'usuarios/editar/:id', to: "usuarios#update"
  # ao se utilizar rotas que possuem parametros, coloca-las por ultimo
  # se não o Rails vai confundir o nome da rota com um parametro
  get 'usuarios/:id', to: "usuarios#show", as: :show_usuario
  delete 'usuarios/:id', to: "usuarios#destroy", as: :destroy_usuario
  get 'usuarios', to: "usuarios#index", as: :index_usuarios

end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_secure_password

  mount_uploader :avatar, AvatarUploader

  # macro de associacao, dependent destroy apaga todos os posts escritos
  # por determinado usuario
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :cidade, optional: true

  validates_presence_of :avatar
  validates :nome, presence: true, length: { in: 2..20 }
  validates :sobrenome, presence: true, length: { in: 2..50 }
  validates :email, presence: true, length: { in: 5..50 }, uniqueness: true
  validates :telefone, presence: true, numericality: { only_integer: true },
    length: { in: 8..15 }
  validates :data_nascimento, presence: true
  validates :password, length: { in: 6..12 }, allow_nil: true
  validate :data_correta_maioridade
  validate :data_correta_passado
  validate :tamanho_foto

  def data_correta_maioridade
    if data_nascimento && data_nascimento > (DateTime.now - 18.years)
      errors.add(:data_nascimento, "não pode ter menos de 18 anos")
    end
  end

  def data_correta_passado
    if data_nascimento && data_nascimento < (DateTime.now - 150.years)
      errors.add(:data_nascimento, "você é uma múmia")
    end
  end

  def tamanho_foto
    if avatar.size > 5.megabytes
      errors.add(:avatar, "muito grande, não pode possuir mais de 5 MB")
    end
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]
  before_action :usuario_nao_logado, except: [:new, :create, :buscacidades]
  before_action :usuario_logado, only: [:new, :create]
  before_action :usuario_correto, only: [:edit, :update]
  before_action :usuario_correto_ou_admin, only: :destroy

  # PATCH buscacidades
  def buscacidades
    estado = Estado.find_by(id: params[:estado])
    cidades = estado.cidades if estado

    @result = []
    if cidades
      cidades.each do |cidade|
        @result.append cidade
      end
    end

    respond_to do |format|
      format.json { render json: @result }
    end
  end

  # GET usuarios/novo
  def new
    @usuario = Usuario.new
  end

  # POST usuarios/novo
  def create
    @usuario = Usuario.new(usuario_params)
    if @usuario.save
      flash[:notice] = "Bem vindo à SocialzIN."
      log_in @usuario
    else
      flash.now[:notice] = "Algo errado aconteceu."
      render "new"
    end
  end

  # GET usuarios/1
  def show
    # find eh utilizado para encontrar um registro do bd pelo seu id apenas
  end

  # GET usuarios/editar/1
  def edit
  end

  # PATCH usuarios/editar/1
  def update
    if @usuario.update_attributes(usuario_params)
      redirect_to show_usuario_path(id: @usuario.id)
    else
      render "edit"
    end
  end

  # GET usuarios
  def index
    @usuarios = Usuario.all
  end

  # DELETE usuarios/1
  def destroy
    if @usuario.destroy
      redirect_to index_usuarios_path
    else
      redirect_to show_usuario_path(id: @usuario.id)
    end
  end

  private

  def set_usuario
    @usuario = Usuario.find(params[:id])
  end

  # este metodo impede que parametros indesejados entrem no nosso bd
  # boa pratica de seguranca
  def usuario_params
    params.require(:usuario).permit(:nome, :sobrenome, :email, :data_nascimento,
      :telefone, :password, :password_confirmation, :avatar, :cidade_id)
  end

  def usuario_correto
    if current_user != @usuario
      flash[:alert] = "Não permitido."
      redirect_to show_usuario_path(id: current_user.id)
    end
  end

  def usuario_correto_ou_admin
    if !current_user.admin && current_user != @usuario
      flash[:alert] = "Não permitido."
      redirect_to show_usuario_path(id: current_user.id)
    elsif current_user == @usuario && current_user.admin
      flash[:alert] = "Não permitido."
      redirect_to show_usuario_path(id: current_user.id)
    end
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<!-- Operador ternário
  x = if a == 2 then b else c end
  é equivalente à
  x = a == 2 ? b : c -->
<%= form_for @usuario,
  url: @usuario.persisted? ? :edit_usuario : :new_usuario do |form| %>

  <% if @usuario.errors.any? && @usuario.errors[:avatar] %>
    <%= form.label "Foto de perfil #{@usuario.errors[:avatar].first}" %>
  <% else %>
    <%= form.label "Foto de perfil" %>
  <% end %>
  <%= form.file_field :avatar %>
  <br>

  <% if @usuario.errors.any? && @usuario.errors[:nome] %>
    <%= form.label "Nome #{@usuario.errors[:nome].first}" %>
  <% else %>
    <%= form.label "Nome" %>
  <% end %>
  <%= form.text_field :nome %>
  <br>

  <% if @usuario.errors.any? && @usuario.errors[:sobrenome] %>
    <%= form.label "Sobrenome #{@usuario.errors[:sobrenome].first}" %>
  <% else %>
    <%= form.label "Sobrenome" %>
  <% end %>
  <%= form.text_field :sobrenome %>
  <br>

  <% if @usuario.errors.any? && @usuario.errors[:email] %>
    <%= form.label "Email #{@usuario.errors[:email].first}" %>
  <% else %>
    <%= form.label "Email" %>
  <% end %>
  <%= form.email_field :email %>
  <br>

  <% if @usuario.errors.any? && @usuario.errors[:telefone] %>
    <%= form.label "Telefone #{@usuario.errors[:telefone].first}" %>
  <% else %>
    <%= form.label "Telefone" %>
  <% end %>
  <%= form.text_field :telefone %>
  <br>

  <% if @usuario.errors.any? && @usuario.errors[:data_nascimento] %>
    <%= form.label "Data de Nascimento #{@usuario.errors[:data_nascimento].first}" %>
  <% else %>
    <%= form.label "Data de Nascimento" %>
  <% end %>
  <%= form.date_field :data_nascimento %>
  <br>

  <% if @usuario.errors.any? && @usuario.errors[:password] %>
    <%= form.label "Senha #{@usuario.errors[:password].first}" %>
  <% else %>
    <%= form.label "Senha" %>
  <% end %>
  <%= form.password_field :password %>
  <br>

  <% if @usuario.errors.any? && @usuario.errors[:password_confirmation] %>
    <%= form.label "Confirmação de Senha #{@usuario.errors[:password_confirmation].first}" %>
  <% else %>
    <%= form.label "Confirmação de Senha" %>
  <% end %>
  <%= form.password_field :password_confirmation %>
  <br>

  <%= form.label "Estado" %>
  <%= select("", "estado_id", Estado.all.collect {|estado| [ estado.uf,
    estado.id ] }, {include_blank: "Estado"}, id: :estado) %>
  <br>

  <%= form.label "Cidade" %>
  <select name="usuario[cidade_id]" id="cidade" disabled>
		<option value=""></option>
	</select>
  <br>

  <% if @usuario.persisted? %>
    <%= form.submit "Atualizar" %>
  <% else %>
    <%= form.submit "Cadastrar" %>
  <% end %>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editar Usuário</h1>

<%= render "form" %>

<%= link_to "Todos os Usuários", index_usuarios_path %>
<%= link_to "Excluir", destroy_usuario_path(id: @usuario.id),
  method: :delete %>

app/views/usuarios/index.html.erb
<h1>Usuarios</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Sobrenome</th>
    <th>Email</th>
    <th>Telefone</th>
    <th>Data de Nascimento</th>
    <th colspan="2">Ações</th>
  </tr>
  <% @usuarios.each do |usuario| %>
    <tr>
      <td><%= link_to usuario.nome, show_usuario_path(id: usuario.id) %></td>
      <td><%= usuario.sobrenome %></td>
      <td><%= usuario.email %></td>
      <td><%= usuario.telefone %></td>
      <td><%= usuario.data_nascimento %></td>
      <td><%= link_to "Editar", edit_usuario_path(id: usuario.id) %></td>
      <td><%= link_to "Excluir", destroy_usuario_path(id: usuario.id),
        method: :delete, data: { confirm: "Tem certeza que deseja excluir o cadastro
        (todos os posts serão excluídos)?" } %></td>
    </tr>
  <% end %>
</table>
<br>

<%= link_to "Novo Usuário", new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>Novo Usuário</h1>

<%= render "form" %>

<%= link_to "Todos os Usuários", index_usuarios_path %>

app/views/usuarios/show.html.erb
<h1><%= @usuario.nome %> <%= @usuario.sobrenome %></h1>

<% if !@usuario.avatar.file.nil? %>
  <%= image_tag @usuario.avatar.thumb.url %>
<% end %>
<br>

<p>Nome: <%= @usuario.nome %></p>
<br>

<p>Sobrenome: <%= @usuario.sobrenome %></p>
<br>

<p>Email: <%= @usuario.email %></p>
<br>

<p>Telefone: <%= @usuario.telefone %></p>
<br>

<p>Data de Nascimento: <%= @usuario.data_nascimento %></p>
<br>

<%= link_to "Todos os Usuários", index_usuarios_path %>
<%= link_to "Editar", edit_usuario_path(id: @usuario.id) %>
<%= link_to "Excluir", destroy_usuario_path(id: @usuario.id),
  method: :delete, data: { confirm: "Tem certeza que deseja excluir o cadastro
  (todos os posts serão excluídos)?" } %>