config/routes.rb
Rails.application.routes.draw do
  root to: "usuarios#index"

  # RedefinirSenha controller
  get 'redefinir_senha/busca', to: "redefinir_senha#busca", as: :redefinir_senha
  post 'redefinir_senha/busca', to: "redefinir_senha#recuperar"

  # Comentarios controller
  resources :comentarios

  # Posts controller
  patch 'curtir/:post_id', to: "posts#curtir", as: :curtir
  patch 'descurtir/:post_id', to: "posts#descurtir", as: :descurtir
  get 'feed', to: "posts#feed", as: :feed
  resources :posts

  # Sessoes controller
  get 'login', to: "sessoes#new", as: :login
  post 'login', to: "sessoes#create"
  delete 'logout', to: "sessoes#destroy", as: :logout

  # Usuarios controller
  patch 'buscacidades', to: "usuarios#buscacidades", as: :buscacidades
  get 'usuarios/novo', to: "usuarios#new", as: :new_usuario
  post 'usuarios/novo', to: "usuarios#create"
  get 'usuarios/editar/:id', to: "usuarios#edit", as: :edit_usuario
  patch 'usuarios/editar/:id', to: "usuarios#update"
  # ao se utilizar rotas que possuem parametros, coloca-las por ultimo
  # se não o Rails vai confundir o nome da rota com um parametro
  get 'usuarios/:id', to: "usuarios#show", as: :show_usuario
  delete 'usuarios/:id', to: "usuarios#destroy", as: :destroy_usuario
  get 'usuarios', to: "usuarios#index", as: :index_usuarios

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :usuario
  has_many :comentarios, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :conteudo, presence: true, length: { in: 1..140 }

  def ultima_atualizacao
    data = "#{updated_at.day}/#{updated_at.month}/#{updated_at.year}"
    hora = "#{updated_at.hour}:#{updated_at.min}"
    "#{data} #{hora}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :usuario_nao_logado
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :usuario_correto, only: [:edit, :update]
  before_action :usuario_correto_ou_admin, only: :destroy

  # PATCH curtir/1
  def curtir
    @post = Post.find_by(id: params[:post_id])
    current_user.likes.build(post_id: params[:post_id]).save

    respond_to do |format|
      format.html { redirect_to feed_path }
      format.js
    end
  end

  # PATCH descurtir/1
  def descurtir
    @post = Post.find_by(id: params[:post_id])
    current_user.likes.find_by(post_id: params[:post_id]).destroy

    respond_to do |format|
      format.html { redirect_to feed_path }
      format.js
    end
  end

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comentario = Comentario.new
    @comentarios = @post.comentarios
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to feed_path, notice: 'Post criado.' }
        format.json { render :show, status: :created, location: @post }
      else
        @posts = Post.all.order(updated_at: :desc)
        format.html { render "feed" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /feed
  def feed
    @post = Post.new
    @posts = Post.all.order(updated_at: :desc).paginate(:page => params[:page],
       :per_page => 10)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:usuario_id, :conteudo)
    end

    def usuario_correto
      if current_user != @post.usuario
        flash[:alert] = "Não permitido."
        redirect_to posts_path
      end
    end

    def usuario_correto_ou_admin
      if !current_user.admin && current_user != @post.usuario
        flash[:alert] = "Não permitido."
        redirect_to posts_path
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>

  <%= hidden_field_tag "post[usuario_id]", current_user.id %>

  <div class="field">
    <% if @post.errors.any? && @post.errors[:conteudo] %>
      <%= form.label "Conteúdo #{@post.errors[:conteudo].first}" %>
    <% else %>
      <%= form.label :conteudo %>
    <% end %>
    <%= form.text_field :conteudo, id: :post_conteudo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_voto.html.erb
<% if current_user.likes.where(post_id: @post.id).empty? %>
  <p id="curtir<%= @post.id %>" >
    <%= link_to "Curtir", curtir_path(post_id: @post.id),
      method: :patch, remote: true,
      authenticity_token: true %> (<%= @post.likes.count %>)
  </p>
<% else %>
  <p id="descurtir<%= @post.id %>" >
    <%= link_to "Descurtir", descurtir_path(post_id: @post.id),
      method: :patch, remote: true,
      authenticity_token: true %> (<%= @post.likes.count %>)
  </p>
<% end %>

app/views/posts/curtir.js.erb
$("#curtir<%= @post.id %>").html("<%= escape_javascript(render('voto')) %>");

app/views/posts/descurtir.js.erb
$("#descurtir<%= @post.id %>").html("<%= escape_javascript(render('voto')) %>");

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/feed.html.erb
<h1>Feed de Notícias</h1>

<%= render "form", post: @post %>
<br>

<% @posts.each do |post| %>
  <p><%= post.conteudo %></p>

  <% @post = post %>
  <%= render "voto" %>

  <p>
    Escrito por <%= link_to post.usuario.nome,
    show_usuario_path(id: post.usuario.id) %>
  </p>
  <p>Última atualização: <%= post.ultima_atualizacao %></p>
  <p>
    <% if current_user == post.usuario %>
      <%= link_to "Editar", edit_post_path(post) %>
    <% end %>
    <% if current_user == post.usuario || current_user.admin %>
      <%= link_to "Excluir", post_path(post), method: :delete,
        data: { confirm: "Tem certeza?" } %>
    <% end %>
  </p>
  <br>

<% end %>

<%= will_paginate @posts %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Conteudo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.usuario.nome %></td>
        <td><%= post.conteudo %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Usuario:</strong>
  <%= @post.usuario.nome %>
</p>

<p>
  <strong>Conteudo:</strong>
  <%= @post.conteudo %>
</p>

<p>
  <%= render "comentarios/form", comentario: @comentario %>
</p>

<p>Comentarios:</p>

<% @comentarios.each do |comentario| %>
  <p><%= comentario.conteudo %></p>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>